### ISSUE TITLE
Linux build failures

### ISSUE THREAD

**Issue by uzadow** [libavg/libavg#606]
We have regular linux build failures, e.g.:

https://www.libavg.de/bb/builders/x64-lnx-incr/builds/2526/steps/shell/logs/stdio

Both incremental and full build are affected.

**Comment by oxullo** [comment]
incremental build is fixed now, keeping this open until the full is fine as well

**Comment by uzadow** [comment]
I just had a chance to look at the images a failed test generates. The failing tests all have black images. There's an environment variable, AVG_BROKEN_READBUFFER, which causes libavg to read from the backbuffer instead of the front buffer. You can try activating that, or fiddle around with display settings...
Oh, and the incremental build's still failing, no change :-/.

**Comment by oxullo** [comment]
buildbot now running on a physical machine, all back to green!
